import { prisma } from "@/lib/db";
import { jsonCached } from "@/lib/query-helpers";

export const dynamic = "force-dynamic";

// GET /api/alerts -> currently active (unresolved) alerts, generated by alerts-engine.ts on each sync.
export async function GET() {
  const alerts = await prisma.alert.findMany({
    where: { resolved: false },
    orderBy: [{ severity: "asc" }, { createdAt: "desc" }],
  });

  return jsonCached({ alerts }, 60);
}
